# Generated by Django 3.0.3 on 2020-02-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_upload_file', models.FileField(upload_to='user_upload_files/%Y%m%d')),
            ],
        ),
    ]
